### ISSUE TITLE
Show benchmark as score

### ISSUE THREAD

**Issue by gregorni** [abb128/LiveCaptions#18]
Show the user a number as the result of their benchmark after running it. This could be a neat benchmarking utility for CPU reviews!

**Comment by abb128** [comment]
The benchmark result tends to have some inconsistency at the moment, on the exact same machine I can get anywhere from 2.1 to 3.0 depending on the distro and what programs are running. I may be making changes that may wildly change the results in the future as well, so that would make it somewhat useless as a benchmark. For now it should just be equivalent to a single-core benchmark.

**Comment by gregorni** [comment]
I'm getting such inconsistencies too, anywhere from 1.88 to 2.14, but I think it would be nice to have the number displayed so that you have a better idea of how well the captions will perform.

**Comment by abb128** [comment]
The result is now shown directly on the success and fail screens in 555b2cf842736f42fbee08cb96e8b1d474730b10

![image](https://user-images.githubusercontent.com/65567823/209478212-693015a3-a8e2-4585-823a-8e6af2f9477c.png)
![image](https://user-images.githubusercontent.com/65567823/209478245-b6e9d750-c779-4b41-a04c-72cacad7eaad.png)
