### ISSUE TITLE
A minor issue with Bluetooth device 

### ISSUE THREAD

**Issue by kha84** [abb128/LiveCaptions#30]
"Caption microphone instead of desktop audio" button does not work with Bluetooth connected JBL Clip3. No matter if I click it or not - the microphone input is not being considered. 

It does work however with my Platronics headphones, who're using their own radio usb dongle.

That is on Ubuntu 22.10

**Comment by abb128** [comment]
If I understand correctly, the bluetooth device needs to be switched to handsfree mode in order to get microphone. I'm not sure this normally works on Linux.

Does your JBL Clip3 microphone work automatically with other apps, for example if you start a google meeting or discord call?

Also, can you try building from source to see if anything is different after 2650a83b94ce4f4119c06bd9e446417b9cd77d33?

**Comment by kha84** [comment]
Sure will try it out. The microphone sound input level is being correctly shown by the gnome settings app

**Comment by kha84** [comment]
Thanks a lot, I installed gnome builder, took the latest version from git (which included aforementioned commit) and followed your build instruction - everything went just seamlessly and that version is perfectly capable to use my BT device.
But you know what, I retested the same with the same version I had before (net.sapples.LiveCaptions 0.2.0 installed from flatpak) and it also worked. 
I'm starting to think that my Ubuntu 22.10 is playing some bad tricks on me. 
Sorry for this hassle (there should be a smile of me doing facepalm).
LiveCaptions and AprilASR are such amazing pieces of software, brilliant work!
