### ISSUE TITLE
Feature Request -   Make LiveCaptions app to be always on top of all applications.

### ISSUE THREAD

**Issue by mizhko** [abb128/LiveCaptions#76]
make LiveCaptions to be always on top of all apps.  When some apps are in normal window or in a full screen.  When I click on video app and caption app disappears as video app plays. I had to use ALT+TAB to pull caption app to front of video app.  It is very annoying, I wish there is way to make caption app to be always on the top of all apps.

That will be good feature.

**Comment by abb128** [comment]
This is already implemented on X11 compositors, and on some Wayland compositors through the use of a plugin (since unlike X11, Wayland has no built-in way to make windows on top):
* GNOME Wayland (currently still needs to be updated for 45) - https://extensions.gnome.org/extension/5775/live-captions-assistant/
* KDE Wayland - https://store.kde.org/p/1989729
